### ISSUE TITLE
incorrect behavior in setPosition

### ISSUE THREAD

**Issue by IgorKorobeynikov** [Guigui220D/zig-sfml-wrapper#38]
with this: `sprite.setPosition(.{ .x = 500, .y = 350 });`
I get this:
![image](https://user-images.githubusercontent.com/73735838/172060959-11944dab-db4c-4cd9-a4e0-62ce4e88a773.png)
But with this: 
```
var vec = sf.Vector2f.new(500, 350);
sprite.setPosition(vec);
```
I get the expected result
![image](https://user-images.githubusercontent.com/73735838/172061024-c854adf6-e3bb-4155-ba70-1f568d972143.png)

**Comment by Guigui220D** [comment]
Thanks for reporting!
The two lines really shouldn't be different, `Vector2f.new(...)` does exactly what you do. I'm going to investigate this on my own pc and see if it happens here too, but it sounds to me like it's a bug outside my wrapper. It may be related with vector2f being a packed struct because I've heard packed struct have lots of bugs.
If you have any new info, keep me updated ^^

**Comment by linux-admin0001** [comment]
> Thanks for reporting! The two lines really shouldn't be different, `Vector2f.new(...)` does exactly what you do. I'm going to investigate this on my own pc and see if it happens here too, but it sounds to me like it's a bug outside my wrapper. It may be related with vector2f being a packed struct because I've heard packed struct have lots of bugs. If you have any new info, keep me updated ^^

Thank you, I appreciate your work

**Comment by linux-admin0001** [comment]
@Guigui220D 
I've been digging into the zig and raylib-zig repositories, and I seem to be sure that this problem is related to this:
[zig issue 1481](https://github.com/ziglang/zig/issues/1481)
[zig issue 10560](https://github.com/ziglang/zig/issues/10560)

**Comment by Guigui220D** [comment]
Both issues were closed and the bug doesn't seem to happen anymore
If it does let's reopen an issue
